# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SFPortfolioApp' do
    # Comment the next line if you don't want to use dynamic frameworks
    use_frameworks!
  
    # Pods for SFPortfolioApp
    pod 'SFBaseKit', '~> 2.1.0'
    pod 'AppCenter'
  end
